---
# roles/webserver/tasks/main.yml FINAL

# Install dependencies
- name: Install required packages
  apt:
    name:
      - nginx
      - mysql-client
      - php-fpm
      - php-mysql
      - unzip
      - wget
      - nfs-common 
    state: present
    update_cache: true

# Mount NFS share for WordPress files
- name: Ensure /var/www/html directory exists
  file:
    path: /var/www/html
    state: directory

- name: Mount NFS share for WordPress
  mount:
    src: "10.2.22.26:/srv/nfs/wordpress"
    path: /var/www/html
    fstype: nfs
    opts: defaults
    state: mounted

# Configure Nginx for WordPress
- name: Copy custom nginx config
  template:
    src: nginx-web.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true

# Install Node Exporter for monitoring
- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move node_exporter binary
  copy:
    remote_src: yes
    src: /tmp/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'

- name: Create systemd service for node_exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target
  notify: Reload systemd

- name: Start and enable node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
