
# Configure Nginx for WordPress
- name: Copy custom nginx config
  template:
    src: nginx-web.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true

