---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Copy custom Nginx load balancer config
  template:
    src: nginx-lb.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx

- name: Enable new site by creating a symbolic link
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true