---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name:   
  template:
    src: nginx-lb.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true
